name: ⏰ Scheduled daily run

on:
  schedule:
    - cron: 0 4 7,21 * *"

permissions:
  contents: write

jobs:
  trigger-tests:
    name: ⏰ Trigger Tests Workflow (QA)
    uses: ./.github/workflows/tests_workflow.yml
    with:
      env: QA
