name: Scheduled DEV Tests

on:
  schedule:
    - cron: "0 4 * * *"

jobs:
  trigger-tests:
    name: ‚è∞ Trigger Tests Workflow (QA)
    uses: ./.github/workflows/tests_workflow.yml
    with:
      env: QA
