name: Scheduling test run
on:
  schedule:
#    - cron: "0 4 * * *"
    - cron: "*/3 * * * *"

  workflow_dispatch:
    inputs:
      env:
        description: Select environment
        type: choice
        required: true
        options:
          - DEV
          - QA
        default: DEV

run-name: "‚è∞ Scheduled test run on ${{ inputs.env || 'DEV' }}"

permissions:
  contents: write

jobs:
  trigger-main:
    name: Trigger Main Workflow
    uses: ./.github/workflows/tests_workflow.yml
    with:
      env: ${{ inputs.env || 'DEV' }}
